# Set the base image
FROM python:3
# Dockerfile author / maintainer 
MAINTAINER Aline Manera <alinefm@linux.vnet.ibm.com> 

# Update application repository list and install the minicrawler app
COPY * /
RUN pip install requests pymongo

CMD [ "python", "./crawler.py" ]
